# Generated by Django 5.2.15 on 2026-06-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancerecord_id_alter_attendancesession_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_teacher_edited',
            field=models.BooleanField(default=False),
        ),
    ]
