# Generated by Django 5.2.15 on 2026-06-21 17:34

import apps.common.id_generator
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=functools.partial(apps.common.id_generator.generate_short_id, *('users', 'User'), **{}), editable=False, max_length=7, primary_key=True, serialize=False),
        ),
    ]
