# Generated by Django 5.2.15 on 2026-06-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('session_started', 'Session Started'), ('attendance_marked', 'Attendance Marked'), ('session_expired', 'Session Expired'), ('added_to_module', 'Added to Module'), ('status_changed', 'Status Changed'), ('face_enrolled', 'Face Enrolled'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
