# Generated by Django 5.2.15 on 2026-06-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_classroom_id_alter_school_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='subject',
        ),
        migrations.AddField(
            model_name='classroom',
            name='begin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='min_attendance_pct',
            field=models.PositiveSmallIntegerField(default=75, help_text='Minimum attendance percentage required (0–100).'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='num_sessions',
            field=models.PositiveIntegerField(default=0, help_text='Total planned sessions for this module.'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='session_time',
            field=models.CharField(choices=[('day', 'Day'), ('evening', 'Evening'), ('night', 'Night')], default='day', max_length=10),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(help_text='Module name, e.g. "Advanced Mathematics"', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
