# Generated by Django 6.0.6 on 2026-06-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.BinaryField()),
                ('enrollment_photo', models.ImageField(blank=True, null=True, upload_to='enrollment_photos/')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Face Encoding',
                'verbose_name_plural': 'Face Encodings',
            },
        ),
    ]
